# Generated by Django 4.1.1 on 2022-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('state_of_origin', models.CharField(max_length=200)),
                ('lga_of_origin', models.CharField(max_length=200)),
                ('residential_address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
