# Generated by Django 4.1.1 on 2022-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='Authorised_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='birth',
            name='certificate_no',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='birth',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='birth',
            name='lga_of_birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='birth',
            name='place_of_issue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='birth',
            name='reg_center',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='birth',
            name='state_of_birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='birth',
            name='town_of_birth',
            field=models.CharField(default='', max_length=200),
        ),
    ]
